version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - C:\studyAndWork\ems_project\db\postgres\data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - '8082:5432'
#
#  book-service:
#    image:
#      javareboot_module14_image_20
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#    ports:
#      - '8081:8081'
#
#    depends_on:
#      - db