server:
  port: 8081
  servlet:
    context-path: /

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.hibernate: ERROR
#    ru.sberbank.jd: info
#  file:
#    path: ./
#    name: ems_project.log

spring:
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:file:./db/db_ems;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  sql.init:
    data-locations: classpath:addUser.sql
    mode: always
  main:
    allow-circular-references: true
